# Generated by Django 5.0 on 2024-01-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("type", models.CharField(max_length=1000)),
                ("country", models.CharField(max_length=1000)),
                ("town", models.CharField(max_length=1000)),
                ("area", models.CharField(max_length=1000)),
                ("landlord", models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
